### ISSUE TITLE
Unable to create new properties or qnodes

### ISSUE THREAD

**Issue by g1eb** [usc-isi-i2/t2wml#470]
Sending a request to the `/api/create_node` endpoint to create new properties or qnodes results in this error:

`save_entry() missing 1 required positional argument: 'property'`

I looked into what is going on in t2wml api and this is probably related to how the new entries are saved in either t2wml backend or the t2wml api. Is it possibly related to the two not being in sync together on the `feature/wikifier_endpoints` branch? This is what I found in the process:

The `save_entry` function signature requires these params: `def save_entry(self, property, data_type=None, *args, **kwargs)`
This is what is sent from the api: `t2wml_settings.wikidata_provider.save_entry(**entity_dict)`

**Comment by devowit** [comment]
should be fixed with latest t2wml-api from development and latest t2wml development

**Comment by g1eb** [comment]
thanks!

**Comment by g1eb** [comment]
I'm still getting this error, this is after updating both t2wml backend and api development branches:
`save_entry() missing 1 required positional argument: 'property'`

**Comment by g1eb** [comment]
this is also fixed now thanks to @devowit, closing the issue
